databases:
  - name: PitchersSolver_DB
    databaseName: pitcherssolver_db
    user: PitchersSolver
    region: singapore

services:
  - type: web
    name: PitchersSolver
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: PitchersSolver_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false